<?php

namespace AppBundle\Repository;

/**
 * TasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('time' => 'ASC'));
    }
}
